### PR TITLE
Github issue #85  Multiple Headroom components in single page

### PR DESCRIPTION
**Pull request by champeng**
Changes for #85 
@KyleAMathews Though I have found a way, via CSS, to have multiple headroom components in single paged and get them stacked instead of overlapping each other, I have tried to fix that in the component itself. Here my pull request for the same. I know it is not the best solution and even the current changes might not be as per your code guidelines and standards. However, this does solve my purpose of having multiple headroom components stacked over each other.
I am not able to test the PR with my application because I didn't found a way to build the component. Please let me know how to build the component to test it against an independent application.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
I added a NPM script for building the src — `npm run build`.

**Comment by champeng** [comment]
Thanks @KyleAMathews However, I am getting following error when using the local build of the components:
`Module build failed: Error: Couldn't find preset "react-hmre" relative to directory "/Users/tom/react-headroom/dist`

**Comment by champeng** [comment]
@KyleAMathews Did you get chance to look at the error?

**Comment by KyleAMathews** [comment]
No I didn't. Sorry but this isn't a high priority for me so I won't be able to help much. This seems like a useful feature though and I'd be happy to accept a PR with the code changes, good docs, and a demo.

**Comment by champeng** [comment]
Cancelling this PR as I am working on more clean way to support multiple headrooms.

**Pull request closed without merging**
