### PR TITLE
Use `shallowequal` instead of `react-addons-pure-render-mixin`

### LINKED ISSUE #95: Use PureComponent over PureRenderMixin
React 15.3.0 introduced `PureComponent`. The cool thing is that `preact-compat` supports that too now. So refactoring react-headroom to use that would get something that works with Preact as well.

### PR DESCRIPTION
**Pull request by bebraw**
This should work better with solutions like Preact.

Closes #95.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by KyleAMathews** [comment]
Publishing new version shortly

**Comment by bebraw** [comment]
Ok, cool.

**Comment by KyleAMathews** [comment]
Published v2.1.3

**Pull request merged**
