### PR TITLE
Convert code to ES6/JSX

### PR DESCRIPTION
**Pull request by thangngoc89**
As discussed in #57 

I can't figured out how to make the demo site work. 

~~`ReactHotAPI is not a function` so I probably drop react-hot-loader and use babel plugin transform react instead~~

~~Another thing is dropping objectAssign as I can see that babel included the polyfill be default.~~

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks fantastic on a quick run through! Thanks!

Don't worry about the website. I need to rebuild that in Gatsby anyways ;-) So just leave the website/hot reloading stuff the same. I'll rip out the hot reloading and convert the website to be built with Gatsby.

**Comment by thangngoc89** [comment]
Forgot the update the original post. I fixed the website with babel...hmre

**Comment by thangngoc89** [comment]
Hi @KyleAMathews ,

any news on this ? I really need a new release which fix the `React.__spread` issue

**Comment by KyleAMathews** [comment]
Merged! I'll cut a new release once https://github.com/KyleAMathews/react-headroom/pull/58 is in.

**Comment by thangngoc89** [comment]
Thanks a lot

**Comment by KyleAMathews** [comment]
Actually just went ahead and published this as 1.8.2 since the other PR will be a major release given it breaks existing behaviors.

**Pull request merged**
