### PR TITLE
Add react 18 support

### PR DESCRIPTION
**Pull request by akkyjumbade**
Allow to support react 18

### CODE REVIEW

**Comment by rafaelderolez** [comment]
@KyleAMathews any chance this could get merged?

(I've been using it with React 18 for quite some time without any issues at all)

**Comment by janczizikow** [comment]
@akkyjumbade thanks you 🙂

**Comment by jonasdahl** [comment]
Thanks for updating and merging this! ⭐ 
I see that there's a Github release for 3.2.1. Will that also be published to NPM @janczizikow @KyleAMathews? Current version on NPM still seems to be 3.2.0

**Comment by janczizikow** [comment]
@jonasdahl yes, my bad I thought I actually already published it 😂

**Comment by janczizikow** [comment]
published 📦

**Comment by jonasdahl** [comment]
Thanks! 🎉

**Pull request merged**
